### ISSUE TITLE
Is it possible to embed this database?

### ISSUE THREAD

**Issue by SKProCH** [edgedb/edgedb-net#14]
I was looking for embedded database (like SQLite or LiteDB). I don't want to install a database core (cluster or something) to target machine. 

Is is possible to use EdgeDB in "portable" mode?

**Comment by quinchs** [comment]
I don't believe theres a portable mode. It's probably best to ask on [the main repository](https://github.com/edgedb/edgedb).

The closest thing I can recommend is [projects](https://www.edgedb.com/docs/intro/projects) which is linked to a EdgeDB instance.

**Comment by SKProCH** [comment]
Ok, thanks
