### ISSUE TITLE
Inserting issue. Task Get cancelled without proper error message while seeding large model

### ISSUE THREAD

**Issue by kunjee17** [edgedb/edgedb-net#25]
**Describe the bug**
I have wrote code to seed data. But for seeding large model, I am getting error that task get canceled. But don't get why. If I re-run the code again it works without any issue. 

**Reproduction**
Error is random and don't appear all the time so don't know what to include. 

```fsharp
let seedAgent = MailboxProcessor.Start(fun inbox  ->
    let client =
        if EnvConfig.isDevelopment then 
            EdgeDBClient()
        else 
            printfn $"conn str : {EnvConfig.dsn}"
            let conn = EdgeDBConnection.FromDSN(EnvConfig.dsn)
            conn.TLSSecurity <- TLSSecurityMode.Insecure
            EdgeDBClient(conn)
    let rec messageLoop() = async {
        let! (replyChannel: AsyncReplyChannel<_>), (msg: Seed.Msg) = inbox.Receive()
        try 
          printfn $"Inserting {msg.Name}"
          let! r = (client.QueryJsonAsync msg.Query) |> Async.AwaitTask
          printfn $"Inserted {msg.Name} ! - {r.Value}"
        with
        | e -> printfn $"Inserting {msg.Name} error - {e.Message}"
        replyChannel.Reply () //To block the application to go out of scope 
        return! messageLoop()
      }

    // start the loop
    messageLoop()
  )
```

**Expected behavior**
It should seed data every time. 

**Versions (please complete the following information):**
OS : Linux / MacOS
EdgeDB Version: "2.9+a3d80ef"
EdgeDB CLI : EdgeDB CLI 2.2.6+7eabbf9
EdgeDB.Net.Driver - 1.0.4
Dotnet - 7.0.101

**Additional context**
Running seed code using dotnet core and F#. Also having server project which also sometime take too much time for first load of data and then becomes comparatively fast. 

I need to seed at least 5 to 6 different Models with nested data types and it will become more and more complex and large. So, need some solution that will hold off until execution works fully.

**Comment by quinchs** [comment]
Does changing the `MessageTimeout` to a higher value in the [`EdgeDBClientPoolConfig`](https://www.edgedb.com/docs/clients/dotnet/config) resolve the issue?

**Comment by kunjee17** [comment]
@quinchs that worked. Can you please guide me to the page giving default values for config so I can set it up according to our requirements. Please feel free to close the issue.

**Comment by quinchs** [comment]
> @quinchs that worked. Can you please guide me to the page giving default values for config so I can set it up according to our requirements. Please feel free to close the issue.

We don't have a page on the docs for this (I will update this soon) but you can find the defaults here https://github.com/edgedb/edgedb-net/blob/dev/src/EdgeDB.Net.Driver/EdgeDBConfig.cs#L110

**Comment by quinchs** [comment]
I'm going to bump the default timeout to 30 seconds as I think this problem has happened more than once
