### ISSUE TITLE
System.Security.Authentication.AuthenticationException on Insert

### ISSUE THREAD

**Issue by jerebear12** [edgedb/edgedb-net#26]
**Describe the bug**
- On insert I get a System.Security.Authentication.AuthenticationException and no data is persisted to the database. 
- *The Auth object is default with priority 1 and method set to Trust.* 
- EdgeDB has crashed in the last few tests after experiencing this as well but I know that's out of the scope of this issue. 

Connection and Query code below.

**Reproduction**
Connection Code

```csharp
private readonly EdgeDBClient _edgeDB;

public Edge() 
{
    var connection = new EdgeDBConnection();
    connection.Hostname = "localhost";
    connection.Database = "edgedb";
    connection.Port = 10700;
    //connection.Password = "password";

    _edgeDB = new EdgeDBClient(connection); 
}
```

Function being called:

```csharp
public async Task AddItem(Item item)
{
    var insertItemQuery = $"insert Item {{ Id := \"{item.Id}\", Name := \"{item.Name}\", Description := \"{item.Description}\", User := (insert User {{ Id := \"{item.User.Id}\", Name := \"{item.User.Name}\", Password := \"{item.User.Password}\", UserName := \"{item.User.UserName}\", Email := \"{item.User.Email}\" }}) }} unless conflict on .Email";

    // Add item
    await _edgeDB.ExecuteAsync(insertItemQuery);
}
```
Screenshot of caller and error msg:
![error](https://user-images.githubusercontent.com/72420925/210389590-63a8eb19-d4dc-4a8b-b9c4-15c7eaadb3a0.JPG)

**Expected behavior**
I expect the item to be added to the database according to the insert command and schema. I at least expect the connection to be made and any errors with my query to be displayed if that's the case. 

**Versions (please complete the following information):**

- EdgeDB Version: 2.9
- EdgeDB CLI Version: 2.2.6
- OS Version: Windows 10 Home 21H2 19044.2364
- EdgeDB.Net.Driver version: 1.0.4
- .NET version: .Net 7.0

**Additional context**
If you need more information let me know!

**Comment by quinchs** [comment]
This error is thrown because of the TLS security mode on your `connection` object. by default, connections are going to be strictly  over SSL and the client uses the `EdgeDBConnection.TLSCertificateAuthority` property to verify the SSL connection. 

If you're using projects, try creating the client without specifying the conncetion. The client will autoresolve your `edgedb.toml` file and pull the connection info from there:
```cs
edgeDB = new EdgeDBClient(); 
```
If your instance is remote, you can specify the certificate on the `TLSCertificateAuthority` prop. 
If you want to connect insecurely, you can specify the `TLSSecurity` like so:
```cs
connection.TLSSecurity = TLSSecurityMode.Insecure;

**Comment by jerebear12** [comment]
I see. I'm getting a System.IO.FileNotFoundException: 'Couldn't resolve edgedb.toml file' without the connection object.

edgedb.toml is in the project directory:

![term](https://user-images.githubusercontent.com/72420925/210394631-3fc648f1-e402-4575-90b2-7dd2203e989a.JPG)

**Comment by quinchs** [comment]
The autoresolve only works if the `edgedb.toml` file is in the executing directory of your app or a parent directory of your app.

If the instance is running on the same machine you can just specify the instance name like so:
```cs
_edgeDB = new EdgeDBClient(EdgeDBConnection.FromInstanceName("EdgeDB"));
``` 

Let me know if this works for you.

**Comment by jerebear12** [comment]
It's working epic-ly. Thanks for the help!
