### ISSUE TITLE
TransactionException without associated inner exception

### ISSUE THREAD

**Issue by goerch** [edgedb/edgedb-net#29]
In one of our tests we are seeing `EdgeDB.TransactionException : Transaction failed 3 time(s)` without associated inner exception.

We believe this is due to this [ExecuteInternalAsync](https://github.com/edgedb/edgedb-net/blob/8cfcc3a247fa36ca1afcfcfa9ea52daca05cf219/src/EdgeDB.Net.Driver/Transaction.cs#L51) missing a return statement similar to that [ExecuteInternalAsync](https://github.com/edgedb/edgedb-net/blob/8cfcc3a247fa36ca1afcfcfa9ea52daca05cf219/src/EdgeDB.Net.Driver/Transaction.cs#L78).

**Comment by quinchs** [comment]
The [ExecuteInternalAsync](https://github.com/edgedb/edgedb-net/blob/8cfcc3a247fa36ca1afcfcfa9ea52daca05cf219/src/EdgeDB.Net.Driver/Transaction.cs#L35) function *without* a return statement is for the `ExecuteAsync` function exposed on the client. That function does not return any query results. 

The `EdgeDB.TransactionException` should have an inner exception attached to it, if it doesn't, thats a bug. Could you share the test code you're running?
