### ISSUE TITLE
Testing on Windows 11 is broken

### ISSUE THREAD

**Issue by goerch** [edgedb/edgedb-net#30]
Just running the tests on a freshly created fork results in 

```
  Nachricht: 
Es kann keine Instanz der Klasse 'EdgeDB.Tests.Integration.ClientTests' erstellt werden. Fehler: System.IO.DirectoryNotFoundException: Couldn't find project directory for [redacted].

  Stapelüberwachung: 
EdgeDBConnection.FromProjectFile(String path) Zeile 371
EdgeDBConnection.ResolveEdgeDBTOML() Zeile 407
EdgeDBClient.ctor(EdgeDBClientPoolConfig clientPoolConfig) Zeile 120
ClientProvider.get_EdgeDB() Zeile 13
ClientTests.ctor() Zeile 21
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Sorry for the German language settings.

**Comment by goerch** [comment]
It looks like we need some EdgeDB toml project file to run integration tests. Is this somewhere available or is there some documentation?

**Comment by quinchs** [comment]
`edgedb.toml` is a EdgeDB project file that lets bindings implicitly connect to your instance. Documentation for this can be found here https://www.edgedb.com/docs/intro/projects and here https://www.edgedb.com/docs/clients/dotnet/index#quickstart

**Comment by goerch** [comment]
OK, it looks like I need to run `edgedb project init` in `edgedb-net`s project folder first before running `dotnet test`.
